name: E2E Tests

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Download github pages artifact
        id: download
        uses: actions/download-artifact@v8
        with:
          name: github-pages
          path: github-pages
      - name: Extract dist from github pages artifact
        run: |
          mkdir dist
          tar -xvf ${{ steps.download.outputs.download-path }}/artifact.tar -C dist
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Serve static site for Playwright tests
        run: |
          npx serve@latest dist &
          sleep 5
      - name: Wait for static site to be up
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000/; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for service to start..."
            sleep 5
          done
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
